services:
  laravel:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    container_name: laravel_user_api
    working_dir: /var/www/laravel
    volumes:
      - .:/var/www/laravel
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: mysql_user_api_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mysql_data:
